const CONSTANTS = {
    CLOCK_INTERVAL_NAME: `__CLOCK_INTERVAL_NAME__`,
    CLOCK_INTERVAL_PROCESS_SEED: `__CLOCK_INTERVAL_PROCESS_SEED`,
    CLOCK_INTERVAL_PORCESS_STACK_NAME: `__CLOCK_INTERVAL_PORCESS_STACK__`
}

export default CONSTANTS
